name: Build MonoGame Shaders

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - run: dotnet tool install --global dotnet-mgcb
    - run: mgcb Content.mgcb /platform:DesktopGL /outputDir:bin/DesktopGL
    - uses: actions/upload-artifact@v4
      with:
        name: Shaders-DesktopGL
        path: bin/DesktopGL/**/*.xnb
